### ISSUE TITLE
Checkbox checkmark is not a displayed in almost all themes ThemeRoller

### ISSUE THREAD

**Issue by SinglWolf** [jquery/download.jqueryui.com#628]
The Checkbox checkbox does not appear in almost all themes.
![Image](https://github.com/user-attachments/assets/fb6bc19f-8d3f-400c-9698-578cda71384f) 
![Image](https://github.com/user-attachments/assets/9d2c6f0a-c336-4e8c-953d-f0c1064e381c)
The problem is that the color parameter is incorrectly specified in
```css
.ui-icon-background,
.ui-state-active .ui-icon-background {
	border: #fbd850;
	background-color: #eb8f00;
}
```
If you change the value of  `background-color` to `#04eb00` ,  checkbox will be displayed.
```css
.ui-icon-background,
.ui-state-active .ui-icon-background {
	border: #fbd850;
	background-color: #04eb00;
}
```
![Image](https://github.com/user-attachments/assets/17ef94bf-f3f5-4586-9d1e-dd903b794650)

I couldn't achieve the same effect in `ThemeRoller`.
